version: 0.2

env:
  variables:
    ECR_REGISTRY: <RCR URL>
    ECR_REPOSITORY: <ECR Repository>
    IMAGE_TAG: latest
    CONTAINER_NAME: <private Repository name>

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
  build:
    commands:
      - docker build -t container-test-app:${IMAGE_TAG} -f Dockerfile .
      - docker tag container-test-app:${IMAGE_TAG} ${ECR_REPOSITORY}:${IMAGE_TAG}
  post_build:
    commands:
      - docker push ${ECR_REPOSITORY}:${IMAGE_TAG}
      - printf '[{"name":"%s","imageUri":"%s:%s"}]' "$CONTAINER_NAME" "$ECR_REPOSITORY" "$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json